---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres16
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.5-1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 22Gi
    storageClass: database
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
