---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age168cakqlgja3ma3kh0l4cdzs64ymmz83gfht478k6grru32u5es0qzcu743"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age168cakqlgja3ma3kh0l4cdzs64ymmz83gfht478k6grru32u5es0qzcu743"
